options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_API_VERSION=1.41'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/gcp-devops-project/my-app:$SHORT_SHA'
      - '.'

  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_API_VERSION=1.41'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/gcp-devops-project/my-app:$SHORT_SHA'

  # 3. Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - '-c=k8s-devops'
      - '-l=us-central1-a'
      - '-f=gke-app.yaml'
      - '-i=us-central1-docker.pkg.dev/$PROJECT_ID/gcp-devops-project/my-app:$SHORT_SHA'
      - '-n=gcp-devops-prod'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/gcp-devops-project/my-app:$SHORT_SHA'