options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcp-devops-project/my-app:$SHORT_SHA', '.' ]
  
  - name: 'docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcp-devops-project/my-app:$SHORT_SHA' ]

  # - name: 'docker'
  #   args: ['login', '-u', 'oauth2accesstoken', '-p', '$(gcloud auth print-access-token)', 'https://us-central1-docker.pkg.dev']

  - name: "gke-deploy"
    args:
      - "--cluster=k8s-devops"
      - "--location=us-central1-a"
      - "--manifest=gke-app.yaml"
      - "--image=us-central1-docker.pkg.dev/$PROJECT_ID/gcp-devops-project/my-app:$SHORT_SHA"
      - "--namespace=gcp-devops-prod"

# images: 
#   - 'us-central1-docker.pkg.dev/$PROJECT_ID/gcp-devops-project/my-app:$SHORT_SHA'