steps:
  - name: 'docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp-devops', '.' ]
  
  # - name: 'docker'
  #   args: ['push', 'gcr.io/$PROJECT_ID/gcp-devops' ]

images: 
  - 'us-central1-docker.pkg.dev/my-project-9303-1756152833853/gcp-devops-project'