options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcp-devops:$SHORT_SHA', '.' ]
  
  # - name: 'docker'
  #   args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcp-devops:$SHORT_SHA' ]
  # - name: 'docker'
  #   args: ['login', '-u', 'oauth2accesstoken', '-p', '$(gcloud auth print-access-token)', 'https://us-central1-docker.pkg.dev']


images: 
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/gcp-devops'