options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_NAME: "us-central1-docker.pkg.dev/my-project-9303-1756152833853/gcp-devops-project/my-app"

steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_API_VERSION=1.41'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME}:$SHORT_SHA'
      - '.'

  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_API_VERSION=1.41'
    args:
      - 'push'
      - '${_IMAGE_NAME}:$SHORT_SHA'

  # 3. Deploy to GKE
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
      - 'run'
      - '-c=k8s-devops'
      - '-l=us-central1-a'
      - '-f=gke-app.yaml'
      - '-i=${_IMAGE_NAME}:$SHORT_SHA'
      - '-n=gcp-devops-prod'

images:
  - ${_IMAGE_NAME}:$SHORT_SHA
  - ${_IMAGE_NAME}:latest