steps:
  - name: 'docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/my-project-9303-1756152833853/gcp-devops-project', '.' ]
  
  - name: 'docker'
    args: ['push', 'us-central1-docker.pkg.dev/my-project-9303-1756152833853/gcp-devops-project' ]

images: 
  - 'us-central1-docker.pkg.dev/my-project-9303-1756152833853/gcp-devops-project'