apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
  namespace: gcp-devops-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: gcp-devops-gke
        image: us-central1-docker.pkg.dev/my-project-9303-1756152833853/gcp-devops-project/my-app:$SHORT_SHA
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-gke-service
  namespace: gcp-devops-prod
  labels:
    app: gcp
    kubernetes.io/managed-by: gke-deploy
spec:
  type: LoadBalancer
  selector:
    app: gcp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000